steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/rent-application-9a1da/rent-app-backend:latest'
    - '-f'
    - 'apps/backend/Dockerfile'
    - '.'
images:
  - 'gcr.io/rent-application-9a1da/rent-app-backend:latest'
